source $SETUP_SITE_TOP/pathmunge.sh

# Setup EDMDATAFILES path for LCLS Home
export TOOLS=/reg/g/pcds/package/epics/lcls/tools
export EDM=$TOOLS/edm/display

export EDMDATAFILES=
edmpathmunge $EDM/mgnt
edmpathmunge $EDM/slc
edmpathmunge $EDM/install
edmpathmunge $EDM/event
edmpathmunge $EDM/vac
edmpathmunge $EDM/lcls
edmpathmunge $EDM/pps
edmpathmunge $EDM/bcs
edmpathmunge $EDM/mps
edmpathmunge $EDM/bpms
edmpathmunge $EDM/llrf
edmpathmunge $EDM/prof
edmpathmunge $EDM/laser
edmpathmunge $EDM/mc
edmpathmunge $EDM/ws
edmpathmunge $EDM/watr
edmpathmunge $EDM/temp
edmpathmunge $EDM/alh
edmpathmunge $EDM/blm
edmpathmunge $EDM/toroid
edmpathmunge $EDM/misc
edmpathmunge $EDM/fbck
edmpathmunge $EDM/und
edmpathmunge $EDM/cud
edmpathmunge $EDM/cf
edmpathmunge $EDM/xray
edmpathmunge $EDM/knob
edmpathmunge $EDM/autosave
edmpathmunge $EDM/ads
edmpathmunge $EDM/camac
edmpathmunge $EDM/photon_diag
edmpathmunge $EDM/klys
edmpathmunge $EDM/ntwk
edmpathmunge $EDM/rm
edmpathmunge $EDM/cryo
edmpathmunge $EDM/gadc
edmpathmunge $EDM
edmpathmunge ..
edmpathmunge .
